name: Deploy using Github Actions

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Test
        run: |
          npm run build --if-present
          npm test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
